---
# tasks file for control
- name: install tools
  apt: name={{item}} state=present update_cache=true
  become: true
  with_items:
   - curl
   - tree
- name: "add Python 2.7 repo"
  command: "add-apt-repository -y ppa:fkrull/deadsnakes-python2.7"
  become: true
- name: Upgrade Python package to the latest version
  apt:
   name: "python2.7"
   state: latest
   update_cache: yes
   force: yes
  become: true
- name: Install Python PIP
  apt:
   name: "python-pip"
   state: latest
   update_cache: yes
   force: yes
  become: true
- name: Install docker Python module
  pip:
   name: docker
  become: true
- name: Install docker-compose Python module
  pip:
   name: docker-compose>1.7.0
  become: true
